// Generated by CoffeeScript 1.8.0
(function() {
  var API_LIVE_URL, API_SANDBOX_URL, API_VERSION, PayPal, querystring, request, util, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  request = require('request');

  querystring = require('querystring');

  _ = require('underscore');

  util = require('util');

  API_LIVE_URL = 'https://api-3t.paypal.com/nvp';

  API_SANDBOX_URL = 'https://api-3t.sandbox.paypal.com/nvp';

  API_VERSION = 94;

  PayPal = (function() {
    function PayPal(options) {
      this.call = __bind(this.call, this);
      this.apiUrl = options.live ? API_LIVE_URL : API_SANDBOX_URL;
      this.username = options.username;
      this.password = options.password;
      this.signature = options.signature;
    }

    PayPal.prototype.call = function(method, parameters, callback) {
      var args, k, processResponse, v;
      processResponse = function(text) {
        var data, ids, k, p, params;
        data = querystring.decode(text);
        if (data == null) {
          return typeof callback === "function" ? callback('invalid server response') : void 0;
        }
        params = (((function() {
          var _results;
          _results = [];
          for (k in data) {
            _results.push(k);
          }
          return _results;
        })()).map(function(key) {
          var parts;
          parts = /L_([A-Z]+)(\d+)/.exec(key);
          if (parts) {
            return [parts[1], parseInt(parts[2]), key];
          } else {
            return null;
          }
        })).filter(function(p) {
          return p != null;
        });
        ids = (_.uniq(_.flatten((function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = params.length; _i < _len; _i++) {
            p = params[_i];
            _results.push(p[1]);
          }
          return _results;
        })()))).filter(function(p) {
          return p != null;
        });
        return ids.map(function(id) {
          var date, obj, param, value, _i, _len;
          obj = {};
          for (_i = 0, _len = params.length; _i < _len; _i++) {
            param = params[_i];
            if (id === param[1]) {
              value = data[param[2]];
              if (!isNaN(value)) {
                value = parseFloat(value);
              }
              if (param[0] === 'TIMESTAMP' || /.+DATE/.test(param[0])) {
                date = new Date(value);
                if (date && !isNaN(date.getYear())) {
                  value = date;
                }
              }
              obj[param[0]] = value;
            }
          }
          return obj;
        });
      };
      args = {
        USER: this.username,
        PWD: this.password,
        SIGNATURE: this.signature,
        METHOD: method,
        VERSION: API_VERSION
      };
      for (k in parameters) {
        v = parameters[k];
        args[k] = v;
      }
      return request.post({
        url: this.apiUrl,
        body: querystring.encode(args)
      }, function(error, response, body) {
        if (error) {
          return typeof callback === "function" ? callback(error) : void 0;
        }
        return typeof callback === "function" ? callback(null, processResponse(body)) : void 0;
      });
    };

    return PayPal;

  })();

  module.exports = PayPal;

}).call(this);
